/**
 * The icon drawn in the middle of each emblem. Icons are from game-icons.net
 * (CC BY 3.0) through `react-icons/gi`; the credit is in the Trophy cabinet tab
 * and in `public/CREDITS.md`. One entry per shared `EmblemGlyph` key, so a
 * glyph added to the catalog without an icon fails the type-check.
 */
import type { IconType } from 'react-icons';
import {
  GiAlarmClock,
  GiAnchor,
  GiAngelWings,
  GiBowTie,
  GiBroadheadArrow,
  GiBurningMeteor,
  GiCaptainHatProfile,
  GiCarWheel,
  GiCheeseWedge,
  GiClaws,
  GiClawHammer,
  GiClover,
  GiCoins,
  GiCrackedShield,
  GiFist,
  GiFlame,
  GiHorseHead,
  GiHorseshoe,
  GiImperialCrown,
  GiKnapsack,
  GiLaurelsTrophy,
  GiLightProjector,
  GiMeatCleaver,
  GiMoon,
  GiOpenTreasureChest,
  GiOwl,
  GiPodiumWinner,
  GiPokerHand,
  GiRainbowStar,
  GiRat,
  GiRobberMask,
  GiRocket,
  GiScrollUnfurled,
  GiSnakeTongue,
  GiSofa,
  GiStoneBlock,
  GiStoneThrone,
  GiSwallow,
  GiSwapBag,
  GiTropicalFish,
  GiUpgrade,
  GiWarPick,
  GiWaterSplash,
  GiWhaleTail,
  GiWolfTrap,
} from 'react-icons/gi';
import type { EmblemGlyph } from '@poker/shared';

export const EMBLEM_GLYPHS: Readonly<Record<EmblemGlyph, IconType>> = {
  // Career
  armchair: GiSofa,
  'card-fan': GiPokerHand,
  owl: GiOwl,
  'money-bag': GiSwapBag,
  spotlight: GiLightProjector,
  'robber-mask': GiRobberMask,
  'coin-stack': GiCoins,
  fish: GiTropicalFish,
  fist: GiFist,
  mousetrap: GiRat,
  'upward-arrows': GiUpgrade,
  'captain-hat': GiCaptainHatProfile,
  claws: GiClaws,
  'bear-trap': GiWolfTrap,
  pickaxe: GiWarPick,
  arrow: GiBroadheadArrow,
  'water-splash': GiWaterSplash,
  anchor: GiAnchor,
  'four-leaf-clover': GiClover,
  knapsack: GiKnapsack,
  'bow-tie': GiBowTie,
  horseshoe: GiHorseshoe,
  throne: GiStoneThrone,
  'alarm-clock': GiAlarmClock,
  scroll: GiScrollUnfurled,
  'treasure-chest': GiOpenTreasureChest,
  // Feats
  cheese: GiCheeseWedge,
  cleaver: GiMeatCleaver,
  'stone-block': GiStoneBlock,
  wheel: GiCarWheel,
  hammer: GiClawHammer,
  'cracked-shield': GiCrackedShield,
  'snake-bite': GiSnakeTongue,
  rocket: GiRocket,
  flame: GiFlame,
  podium: GiPodiumWinner,
  rainbow: GiRainbowStar,
  'horse-head': GiHorseHead,
  whale: GiWhaleTail,
  bird: GiSwallow,
  moon: GiMoon,
  'angel-wings': GiAngelWings,
  crown: GiImperialCrown,
  meteor: GiBurningMeteor,
  'laurel-trophy': GiLaurelsTrophy,
};
